name: 'Get Job URL'
description: 'Get job url'
inputs:
  github_token:
    description: "github token"
    required: true
  job_name:
    description: 'job name'
    required: true
outputs:
  job_url:
    description: "job url"
    value: ${{ steps.job-url.outputs.result }}
runs:
  using: "composite"
  steps:
    - name: Get Job URL
      id: job-url
      uses: actions/github-script@v6
      with:
        github-token: '${{ inputs.github_token }}'
        result-encoding: string
        script: |
          const result = await github.rest.actions.listJobsForWorkflowRun({
            owner: context.repo.owner,
            repo: context.repo.repo,
            run_id: context.runId,
          });

          console.log(JSON.stringify(result))
          console.log(`Searching for job named: ${{ inputs.job_name }}`)
          var jobUrl;
          for (const {name, html_url} of result.data.jobs) {
              if (name == '${{ inputs.job_name }}') {
                  jobUrl = html_url
                  break;
              }
          }
          console.log(`jobUrl: ${jobUrl}`)
          return jobUrl
